### PR TITLE
feat/AUT-2524 enchantment of language plugin

### PR DESCRIPTION
**Pull request by meefox**
Related to https://oat-sa.atlassian.net/browse/AUT-2524
Main description https://github.com/oat-sa/extension-tao-depp/pull/360

## What is the purpose of this pull request?
New feature

## What changes did you make?

Added label for the selected language,
added highlight marking for blocks with applied languages

## Which issues does your PR resolve?
AUT-2524

3/3

### CODE REVIEW

**Review by shaveko — APPROVED** [review]
Looks good, checked the demo shown by @meefox

**Comment by shaveko** [comment]
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Review by bziondik — APPROVED** [review]
LGTM

**Comment by AntonNeviarouski** [comment]
QA verified

**Pull request merged**
